geneservice.elasticsearch.index-prefix=geneservice
%test.geneservice.elasticsearch.index-prefix=test-geneservice

geneservice.data-dir=./data

quarkus.elasticsearch.hosts=0.0.0.0:9200
%prod.quarkus.elasticsearch.hosts=es:9200

quarkus.http.cors=true
quarkus.http.cors.origins=*

%dev.quarkus.log.category."ibb.api.geneservice".level=DEBUG

quarkus.container-image.registry=docker.gitlab.gwdg.de
quarkus.container-image.group=ibb/api
